# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35e646725178bde83ce871d088c970d2f8181e589fb2b1e845a7798a50b373b3fb5f7ac1484f2356a1371898a1774b29cde124cc628bf8078269bc231897ea6f

test:
  secret_key_base: 5593d636df150415892ec5f327e275b53387c6d72aa3d409228b2c2610e04264c57c46d76a544de36a86fb11a1c4567f953a25e8ab87a3e6acbbebd7d878b7ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
